// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUTs87HGVx8ppTOcXWsw5taRZ6u3yRpPY',
    appId: '1:828187567117:web:c02028f5fa7337d15f6144',
    messagingSenderId: '828187567117',
    projectId: 'teacher-management-syste-f8043',
    authDomain: 'teacher-management-syste-f8043.firebaseapp.com',
    storageBucket: 'teacher-management-syste-f8043.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjpR3cYDp8M1JHpujHcEZebtjJd6ifvaE',
    appId: '1:828187567117:android:2fa18e0e43bd98a15f6144',
    messagingSenderId: '828187567117',
    projectId: 'teacher-management-syste-f8043',
    storageBucket: 'teacher-management-syste-f8043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-kWHG3Vyi4HfAlr4J6rgLfZhYOt9QqMQ',
    appId: '1:828187567117:ios:a47bdd5b8a7a08da5f6144',
    messagingSenderId: '828187567117',
    projectId: 'teacher-management-syste-f8043',
    storageBucket: 'teacher-management-syste-f8043.firebasestorage.app',
    iosBundleId: 'com.example.teacherManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-kWHG3Vyi4HfAlr4J6rgLfZhYOt9QqMQ',
    appId: '1:828187567117:ios:a47bdd5b8a7a08da5f6144',
    messagingSenderId: '828187567117',
    projectId: 'teacher-management-syste-f8043',
    storageBucket: 'teacher-management-syste-f8043.firebasestorage.app',
    iosBundleId: 'com.example.teacherManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUTs87HGVx8ppTOcXWsw5taRZ6u3yRpPY',
    appId: '1:828187567117:web:257714fc2df75a095f6144',
    messagingSenderId: '828187567117',
    projectId: 'teacher-management-syste-f8043',
    authDomain: 'teacher-management-syste-f8043.firebaseapp.com',
    storageBucket: 'teacher-management-syste-f8043.firebasestorage.app',
  );
}
